### ISSUE TITLE
Anyone interested in being the recommended fork for this repo?

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-integration-giphy#12]
Hi everyone, 

This repo was created to offer sample code for outgoing webhooks. It's served it's purpose and there's a growing community of apps now. 

The core team is investing in building out the platform and maintaining this repo isn't a priority. 

Would anyone in the community be interested in becoming the official fork of this project? 

We'd reference your work in the README similar to [mattermost-integration-gitlab](https://github.com/mattermost/mattermost-integration-gitlab).

**Comment by Lujeni** [comment]
Hello @it33,

[Numberly](https://github.com/numberly) are interested to become the official fork: [here](https://github.com/numberly/mattermost-integration-giphy)

We try to backport issues from this repository and improved the package:
- https://github.com/numberly/mattermost-integration-giphy/issues/5 (add python packaging)
- https://github.com/numberly/mattermost-integration-giphy/issues/3 (fix https://github.com/mattermost/mattermost-integration-giphy/pull/10)
- https://github.com/numberly/mattermost-integration-giphy/issues/1 (slash command)

We use mattermost throught the gitlab omnibus.
We support some tools around mattermost also:
- https://github.com/numberly/matterhook
- https://github.com/Lujeni/matterllo

You can ping me on IRC (`Lujeni`) if you need more details.
Regard

**Comment by it33** [comment]
Thanks @Lujeni!
